modLoader="javafml"
loaderVersion="[52,)"
license="MIT"

[[mods]]
modId="totemfactory"
version="1.1"
displayName="Create: Totem Factory"
displayURL="https://modrinth.com/mod/create-totem-factory"
credits=""
authors="\nMarcosJoestar, jargames99 & Mystic Creations Team"
description="The industrial revolution has come to Minecraft, and with it, new knowledge and discoveries both in the field of science and magic."

[[dependencies.totemfactory]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.totemfactory]]
modId="create"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.totemfactory]]
modId="create_enchantment_industry"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"


